# Generated by Django 4.1.7 on 2023-04-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dellapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=250)),
                ('img1', models.ImageField(upload_to='pics')),
                ('desc1', models.TextField()),
            ],
        ),
    ]
